name: hf-gs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - plyfile
  - python=3.8.1
  - pip
  - pytorch=2.1.2
  - torchaudio=2.1.2
  - torchvision=0.16.2
  - pytorch-cuda=11.8
  - tqdm
  - pip:
      - gaussian_splatting/submodules/diff-gaussian-rasterization-confidence
      - gaussian_splatting/submodules/simple-knn
      - gaussian_splatting/submodules/pytorch3d
      - matplotlib
      - torchmetrics
      - timm
      - opencv_python
      - imageio
      - open3d
      - huggingface-hub==0.24.7
      - gdown
      - zipp
      - easydict==1.9.0
      - diffusers==0.27.2
      - lpips
      - pandas
      - albumentations==0.5.2
      - hydra-core
      - pytorch-lightning==1.2.9
      - tabulate
      - kornia==0.5.0
      - webdataset
      - packaging
      - scikit-image==0.17.2
      - scikit-learn==0.24.2
      - wldhx.yadisk-direct
      - numpy==1.23.2
      - joblib
      - tabulate
      - webdataset
      - transformers==4.40.2
      - accelerate==1.0.1